# Generated by Django 5.2.11 on 2026-02-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_share'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='follow',
            new_name='posts_follo_followe_28b9fa_idx',
            old_name='posts_follo_followe_37fe19_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='posts_follo_followi_e74ed3_idx',
            old_name='posts_follo_followi_8ef855_idx',
        ),
    ]
