# Generated by Django 5.2.11 on 2026-02-26 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tutorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF or DOCX).', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the resume was last uploaded.', null=True),
        ),
    ]
