# Generated by Django 5.2.11 on 2026-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_resume_userprofile_resume_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='Designates if the user has completed the onboarding flow.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('ADMIN', 'Admin'), ('ORG_ADMIN', 'Organization Admin')], default='STUDENT', help_text='Role of the user on the platform.', max_length=10),
        ),
    ]
