# Generated by Django 5.1.7 on 2026-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_onboarded_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Designates if the user wants to receive email alerts for missed messages.'),
        ),
    ]
