# Generated by Django 5.1.7 on 2026-04-07 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aptitude', '0002_aptitudequizattempt_aptitudequizresponse'),
        ('organizations', '0008_subscriptionplan_ai_tokens_monthly'),
        ('practice', '0002_company_topic_alter_testcase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Instructions for the test taker.')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Test duration in minutes.')),
                ('enable_proctoring', models.BooleanField(default=True, help_text='Track tab-switches and require full-screen.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aptitude_problems', models.ManyToManyField(blank=True, related_name='assessments', to='aptitude.aptitudeproblem')),
                ('coding_problems', models.ManyToManyField(blank=True, related_name='assessments', to='practice.problem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_window', models.DateTimeField(help_text='When students can start taking the test.')),
                ('end_window', models.DateTimeField(help_text='When the test becomes completely unavailable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.assessment')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_window'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Not Started)'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto-submitted (Time Expired)'), ('VIOLATION_BLOCKED', 'Blocked due to proctoring violation')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('aptitude_score', models.FloatField(default=0, help_text='Pre-calculated aptitude score')),
                ('coding_score', models.FloatField(default=0, help_text='Pre-calculated coding score')),
                ('total_score', models.FloatField(default=0)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessmentassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('assignment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'CS Class of 2026', 'Q1 New Hires'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Students in this specific cohort.', related_name='cohorts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.cohort'),
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BLUR', 'Window Lost Focus / Tab Switch'), ('EXIT_FULL_SCREEN', 'Exited Full Screen Mode'), ('COPY_PASTE', 'Attempted Copy/Paste')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Extra details regarding the violation.')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='assessments.assessmentattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
