# Generated by Django 5.1.7 on 2026-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringlog',
            name='snapshot',
            field=models.ImageField(blank=True, help_text='WebRTC snapshot capture', null=True, upload_to='proctoring_snapshots/'),
        ),
        migrations.AlterField(
            model_name='proctoringlog',
            name='event_type',
            field=models.CharField(choices=[('BLUR', 'Window Lost Focus / Tab Switch'), ('EXIT_FULL_SCREEN', 'Exited Full Screen Mode'), ('COPY_PASTE', 'Attempted Copy/Paste'), ('WEBCAM_SNAPSHOT', 'Webcam Snapshot')], max_length=50),
        ),
    ]
