# Generated by Django 5.2.11 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_subscription_user_subscriptionplan_target_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("STARTER", "Starter"),
                    ("GROWTH", "Growth"),
                    ("ENTERPRISE", "Enterprise"),
                    ("PRO", "Pro"),
                    ("PERSONAL_PRO", "Personal Pro"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
