# Generated by Django 5.2.11 on 2026-03-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_update_subscriptionplan_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ORG_CREATED", "Organization Created"),
                            ("INVITE_SENT", "Invitation Sent"),
                            ("INVITE_CANCELLED", "Invitation Cancelled"),
                            ("INVITE_ACCEPTED", "Invitation Accepted"),
                            ("MEMBER_REMOVED", "Member Removed"),
                            ("MEMBER_LEFT", "Member Left"),
                            ("MEMBERSHIP_ROLE_CHANGED", "Membership Role Changed"),
                            ("SUBSCRIPTION_PLAN_CHANGED", "Subscription Plan Changed"),
                            ("SUBSCRIPTION_CREATED", "Subscription Created"),
                        ],
                        max_length=40,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="organizationauditlog",
            index=models.Index(fields=["organization", "created_at"], name="organizatio_organiz_4ee58c_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationauditlog",
            index=models.Index(fields=["action", "created_at"], name="organizatio_action_0b4d58_idx"),
        ),
    ]
