# Generated by Django 5.2.11 on 2026-03-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_organizationauditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organizationauditlog",
            new_name="organizatio_organiz_7e0ce7_idx",
            old_name="organizatio_organiz_4ee58c_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationauditlog",
            new_name="organizatio_action_2964c6_idx",
            old_name="organizatio_action_0b4d58_idx",
        ),
    ]
