# Generated by Django 5.2.11 on 2026-03-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_rename_organizatio_organiz_4ee58c_idx_organizatio_organiz_7e0ce7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_step',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOMAIN_SETUP', 'Domain Setup'), ('DOMAIN_VERIFIED', 'Domain Verified'), ('MEMBERS_INVITED', 'Members Invited'), ('COMPLETE', 'Complete')], default='PENDING', help_text='Current onboarding progress.', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified_domain',
            field=models.CharField(blank=True, help_text='Primary verified email domain for this organization (e.g. college.edu).', max_length=120),
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TRAINER', 'Trainer'), ('STUDENT', 'Student')], default='STUDENT', help_text='Role to assign when invitation is accepted.', max_length=15),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('TRAINER', 'Trainer'), ('STUDENT', 'Student'), ('ORG_ADMIN', 'Org Admin (Legacy)'), ('MEMBER', 'Member (Legacy)')], default='STUDENT', max_length=15),
        ),
    ]
