# Generated by Django 5.2.11 on 2026-03-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_add_onboarding_step_and_invite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_tokens_monthly',
            field=models.IntegerField(default=50000, help_text='Max AI tokens per org per month. -1 = unlimited'),
        ),
    ]
