# Generated by Django 5.2.11 on 2026-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_by_message_is_deleted_for_everyone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('ocean', 'Ocean Edge'), ('sunset', 'Sunset'), ('cyberpunk', 'Cyberpunk'), ('forest', 'Forest')], default='default', max_length=20),
        ),
    ]
