# Generated by Django 5.2.11 on 2026-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatthread_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('share_coding_problem', 'Share Coding Problem'), ('share_aptitude_question', 'Share Aptitude Question'), ('share_mock_interview_result', 'Share Mock Interview Result'), ('send_resume', 'Send Resume/JD'), ('tutor_feedback', 'Tutor Feedback Card')], default='text', max_length=32),
        ),
    ]
