# Generated by Django 5.1.7 on 2026-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Designates if a missed-message notification email has been sent.'),
        ),
    ]
