# Generated by Django 5.1.7 on 2026-04-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('ocean', 'Ocean Edge'), ('sunset', 'Sunset'), ('cyberpunk', 'Cyberpunk'), ('forest', 'Forest'), ('cutee', 'Cutee'), ('hands_in_hands', 'Hands in Hands'), ('love_2', 'Love 2'), ('milk_mocha', 'Milk Mocha'), ('red_purple_hearts', 'Red Purple Hearts')], default='default', max_length=20),
        ),
    ]
