# Generated by Django 5.2.7 on 2025-10-25 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['problem', 'order']},
        ),
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for this test case'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Show this test case to users?'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(help_text='Expected output'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(help_text='Input for the test case'),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('description', models.TextField(help_text='Problem statement in HTML or Markdown')),
                ('constraints', models.TextField(blank=True, help_text='Problem constraints')),
                ('example_input', models.TextField(blank=True, help_text='Example input')),
                ('example_output', models.TextField(blank=True, help_text='Example output')),
                ('example_explanation', models.TextField(blank=True, help_text='Explanation for example')),
                ('hints', models.TextField(blank=True, help_text='Hints (one per line or JSON)')),
                ('time_complexity', models.CharField(blank=True, help_text='e.g., O(n log n)', max_length=50)),
                ('space_complexity', models.CharField(blank=True, help_text='e.g., O(n)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('total_accepted', models.PositiveIntegerField(default=0)),
                ('companies', models.ManyToManyField(blank=True, related_name='problems', to='practice.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, related_name='problems', to='practice.topic')),
            ],
            options={
                'ordering': ['problem_number'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach', models.TextField(help_text='Solution approach explanation')),
                ('complexity_analysis', models.TextField(blank=True, help_text='Time and space complexity analysis')),
                ('code_explanation', models.TextField(blank=True, help_text='Line-by-line code explanation')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other video explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial', to='practice.problem')),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='practice.problem'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('compilation_error', 'Compilation Error')], default='pending', max_length=20)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='Memory used in MB', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='practice.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_attempted', 'Not Attempted'), ('attempted', 'Attempted'), ('solved', 'Solved')], default='not_attempted', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('first_solved', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='practice.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_attempted'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python3', 'Python 3'), ('cpp17', 'C++ 17'), ('java', 'Java'), ('javascript', 'JavaScript'), ('c', 'C'), ('csharp', 'C#'), ('go', 'Go'), ('rust', 'Rust')], max_length=20)),
                ('template_code', models.TextField(help_text='Starter code shown to users')),
                ('solution_code', models.TextField(blank=True, help_text='Reference solution (hidden from users)')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_templates', to='practice.problem')),
            ],
            options={
                'ordering': ['problem', 'language'],
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.DeleteModel(
            name='CodingProblem',
        ),
    ]
