# Generated by Django 5.2.11 on 2026-03-05 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0002_mockinterviewsession_extracted_resume_text_and_more'),
        ('organizations', '0008_subscriptionplan_ai_tokens_monthly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('fallback', 'Fallback')], max_length=15)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('operation', models.CharField(choices=[('resume_parse', 'Resume Parse'), ('question', 'Question Generation'), ('closing', 'Closing Message'), ('feedback', 'Feedback Generation'), ('turn_repair', 'Turn Repair'), ('hints', 'Interview Hints'), ('practice', 'Practice Question'), ('health_check', 'Health Check'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Wall-clock time in milliseconds')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('fallback', 'Fallback'), ('quota_exceeded', 'Quota Exceeded')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='mock_interv_organiz_55958e_idx'), models.Index(fields=['user', 'created_at'], name='mock_interv_user_id_e60f36_idx'), models.Index(fields=['operation', 'created_at'], name='mock_interv_operati_3de0da_idx'), models.Index(fields=['provider', 'status'], name='mock_interv_provide_c0c0c7_idx')],
            },
        ),
    ]
