# Generated by Django 5.2.11 on 2026-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0003_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewturn',
            name='band_after_turn',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', help_text='Adaptive band after evaluating this turn.', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='communication_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text="Difficulty of this turn's generated question.", max_length=10),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='technical_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='turn_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='band_confidence',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Confidence (0-100) in current adaptive band assignment.', max_digits=5),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='current_band',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', help_text='Latest adaptive performance band based on turn progression.', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='feedback_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='feedback_status',
            field=models.CharField(default='pending', help_text='Feedback generation lifecycle: pending, processing, ready, failed.', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='performance_band',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', help_text='Current adaptive performance band.', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='selected_pack',
            field=models.CharField(blank=True, default='', help_text='Selected interview pack preset identifier.', max_length=50),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='starting_band',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', help_text='Initial adaptive performance band at session start.', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='strong_skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='weak_skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('FEEDBACK_PROCESSING', 'Feedback Processing'), ('COMPLETED', 'Completed'), ('REVIEW_PENDING', 'Review Pending'), ('REVIEWED', 'Reviewed'), ('CANCELLED', 'Cancelled')], default='STARTED', help_text='Current status of the mock interview session.', max_length=20),
        ),
    ]
