# Generated by Django 5.1.7 on 2026-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0004_interviewturn_band_after_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='code_quality_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='core_cs_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='dbms_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='oops_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='problem_solving_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='rubric_type',
            field=models.CharField(choices=[('faang', 'FAANG Rubric (SDE/MAANG)'), ('service', 'Service Based Rubric (TCS/Infosys)'), ('general', 'General Rubric')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall communication and professional sentiment score.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='system_design_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
